### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by jlaswell** [jlaswell/simple-cache#4]
I'd like to take ownership of this repo, so that I can continue to maintain this spec. Would someone be will to do this?

Thanks!

cc: @bkuhl

**Comment by bkuhl** [comment]
The ball's in your court, accept the transfer.

**Comment by jlaswell** [comment]
Accepted.

![thank you](http://gifs.joelglovier.com/thank-you/thank-you-zach.gif)
